CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE flooding_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    confirmation_votes INTEGER DEFAULT 0,
    actualization_date TIMESTAMP(6),
    registry_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    intensity VARCHAR(255) CHECK (intensity IN ('BAIXA','MEDIA','ALTA','CRITICA')),
    logger VARCHAR(255) NOT NULL,
    neighborhood VARCHAR(255) NOT NULL,
    reference_point VARCHAR(255),
    coordinates GEOMETRY(Point, 4326) NOT NULL
);

CREATE INDEX idx_flooding_points_coordinates ON flooding_points USING GIST (coordinates);